### PR TITLE
fix: remove useless sourcemap url (#43)

### PR DESCRIPTION
**Pull request by tjx666**

### CODE REVIEW

**Review by mdjermanovic — COMMENTED** [review]
Changes LGTM. Can you sign the CLA so we could merge this?

**Comment by mdjermanovic** [comment]
I can see on https://github.com/eslint/espree/pull/567 that the CLA is signed, but here the check says that it still isn't. I'll try close/reopen to update the check.

**Comment by mdjermanovic** [comment]
Close/reopen worked, all green now.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! I'm leaving this open for a couple of days in case someone else wants to take a look

**Review by nzakas — APPROVED** [review]
LGTM.

**Pull request merged**
