### PR TITLE
Breaking: drop node v10/v13/v15 (refs eslint/eslint#14023)

### PR DESCRIPTION
**Pull request by aladdin-add**

### CODE REVIEW

**Review by snitin315 — APPROVED** [review]
LGTM

**Comment by nzakas** [comment]
Let’s make sure we sync these changes with the final changes in the eslint repo

**Comment by brettz9** [comment]
> Let’s make sure we sync these changes with the final changes in the eslint repo

By "final changes", do you just mean whatever the latest is by the time this is merged. With a quick look, I didn't see a current issue or PR to add `engines` changes (so I might track the issue).

**Comment by brettz9** [comment]
Oh, apologies, I guess it must be https://github.com/eslint/eslint/issues/14023 as in this issue title.

**Comment by nzakas** [comment]
Yes, sorry, that’s the correct issue. Was replying on my phone :)

**Review by nzakas — APPROVED** [review]
LGTM. Thanks!

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
